// Mock data + translation matrices for the Nalgonda Real Estate App

export const AGENT = {
  name: 'Nalgonda Properties',
  phone: '+919618339133', // Update with the real agent number
  whatsapp: '919618339133',
};

export const LOCATIONS = [
  'Nalgonda',
  'Miryalaguda',
  'Devarakonda',
  'Suryapet',
  'Bhongir',
  'Choutuppal',
  'Yadagirigutta',
  'Hyderabad',
];

export const PROPERTY_TYPES = ['agriculture', 'plot', 'house'];

export const TRANSLATIONS = {
  en: {
    appName: 'Nalgonda Estates',
    tagline: 'Agricultural Land, Plots & Homes around Nalgonda',
    search: 'Search by village, colony, area...',
    filters: 'Filters',
    location: 'Location',
    allLocations: 'All Locations',
    propertyType: 'Property Type',
    all: 'All',
    agriculture: 'Agricultural Land',
    plot: 'Plot',
    house: 'House',
    sortBy: 'Sort by',
    priceLowToHigh: 'Price: Low to High',
    priceHighToLow: 'Price: High to Low',
    newest: 'Newest First',
    hotDeals: 'Hot Deals',
    featured: '🔥 Hot',
    sold: 'SOLD',
    saved: 'Saved',
    savedListings: 'Saved Listings',
    noSaved: 'No saved properties yet. Tap the heart on any listing.',
    village: 'Village',
    colony: 'Colony / Area',
    costPerAcre: 'Cost per Acre',
    costPerSqYard: 'Cost per Sq. Yard',
    totalArea: 'Total Area',
    builtUpArea: 'Built-up Area',
    plotArea: 'Plot Area',
    totalCost: 'Total Cost',
    acres: 'Acres',
    sqYards: 'Sq. Yards',
    sqft: 'Sq. Ft.',
    call: 'Call',
    sms: 'SMS',
    whatsapp: 'WhatsApp',
    share: 'Share',
    viewDetails: 'View Details',
    showing: 'Showing',
    properties: 'properties',
    noResults: 'No properties match your filters.',
    clearFilters: 'Clear Filters',
    admin: 'Admin',
    backToSite: 'Back to Site',
    agentDashboard: 'Agent Dashboard',
    addListing: 'Add Listing',
    editListing: 'Edit Listing',
    listings: 'Listings',
    actions: 'Actions',
    toggleSold: 'Toggle Sold',
    delete: 'Delete',
    edit: 'Edit',
    save: 'Save',
    cancel: 'Cancel',
    type: 'Type',
    locationLabel: 'Location',
    titleEn: 'Title (English)',
    titleTe: 'Title (Telugu)',
    titleHi: 'Title (Hindi)',
    descEn: 'Description (English)',
    descTe: 'Description (Telugu)',
    descHi: 'Description (Hindi)',
    imageUrls: 'Image URLs (comma separated)',
    hotDeal: 'Hot Deal',
    soldStatus: 'Sold Status',
    login: 'Login',
    password: 'Password',
    enterPassword: 'Enter admin password',
    wrongPassword: 'Incorrect password',
    bedrooms: 'Bedrooms',
    bhk: 'BHK',
    contactAgent: 'Contact Agent',
    poweredBy: 'Built for Nalgonda real estate • Local listings, instant contact',
    language: 'Language',
    English: 'English',
    Telugu: 'Telugu',
    Hindi: 'Hindi',
    priceRange: 'Price Range',
    min: 'Min',
    max: 'Max',
    inquireMsg: 'Hi, I am interested in your property',
    // ---- NEW: Media support ----
    uploadFile: 'Upload Media Files',
    uploadImages: 'Upload Media Files',
    imageHint: 'Upload images and videos. Auto-compressed. Max 500 MB per file.',
    removeImage: 'Remove',
    mediaFile: 'Media File',
    chooseFile: 'Choose File',
    translate: 'Auto-translate to Telugu & Hindi',
    translating: 'Translating…',
    retranslate: 'Re-translate',
    autoTranslated: 'Auto-translated. Edit if needed.',
  },
  te: {
    appName: 'నల్గొండ ఎస్టేట్స్',
    tagline: 'నల్గొండ పరిసరాలలో వ్యవసాయ భూములు, ప్లాట్లు & ఇళ్లులు',
    search: 'గ్రామం, కాలనీ, ప్రాంతం వెతుకండి...',
    filters: 'ఫిల్టర్లు',
    location: 'ప్రాంతం',
    allLocations: 'అన్ని ప్రాంతాలు',
    propertyType: 'ఆస్తి రకం',
    all: 'అన్ని',
    agriculture: 'వ్యవసాయ భూమి',
    plot: 'ప్లాటు',
    house: 'ఇల్లు',
    sortBy: 'క్రమబద్ధీకరణ',
    priceLowToHigh: 'ధర: తక్కువ నుండి ఎక్కువకు',
    priceHighToLow: 'ధర: ఎక్కువ నుండి తక్కువకు',
    newest: 'కొత్తవి మొదట',
    hotDeals: 'హాట్ డీల్స్',
    featured: '🔥 హాట్',
    sold: 'అమ్మబడింది',
    saved: 'సేవ్ చేయబడినవి',
    savedListings: 'సేవ్ చేసిన లిస్టింగ్స్',
    noSaved: 'ఇంకా సేవ్ చేయలేదు. హృదయాన్ని నొక్కండి.',
    village: 'గ్రామం',
    colony: 'కాలనీ / ప్రాంతం',
    costPerAcre: 'ఎకరాకు ధర',
    costPerSqYard: 'చదరపు గజానికు ధర',
    totalArea: 'మొత్తం విస్తీర్ణం',
    builtUpArea: 'నిర్మిత విస్తీర్ణం',
    plotArea: 'ప్లాటు విస్తీర్ణం',
    totalCost: 'మొత్తం ధర',
    acres: 'ఎకరాలు',
    sqYards: 'చదరపు గజాలు',
    sqft: 'చదరపు అడుగులు',
    call: 'కాల్',
    sms: 'ఈమెస్',
    whatsapp: 'వాట్సప్',
    share: 'షేర్',
    viewDetails: 'వివరాలు చూడండి',
    showing: 'చూపుతోంది',
    properties: 'ఆస్తులు',
    noResults: 'ఫిల్టర్లకు సరిపోయే ఆస్తులు లేవు.',
    clearFilters: 'ఫిల్టర్లు తొలగించు',
    admin: 'ఎడ్మిన్',
    backToSite: 'సైట్కు తిరిగి వెళ్ళండి',
    agentDashboard: 'ఏజెంట్ డాష్‌బోర్డ్',
    addListing: 'లిస్టింగ్ జోడించు',
    editListing: 'లిస్టింగ్ మార్చండి',
    listings: 'లిస్టింగ్స్',
    actions: 'చర్యలు',
    toggleSold: 'అమ్మినట్టు/లేదు',
    delete: 'తొలగించు',
    edit: 'మార్చు',
    save: 'సేవ్',
    cancel: 'రద్దు',
    type: 'రకం',
    locationLabel: 'ప్రాంతం',
    titleEn: 'శీర్షిక (ఇంగ్లీషు)',
    titleTe: 'శీర్షిక (తెలుగు)',
    titleHi: 'శీర్షిక (హిందీ)',
    descEn: 'వివరణ (ఇంగ్లీషు)',
    descTe: 'వివరణ (తెలుగు)',
    descHi: 'వివరణ (హిందీ)',
    imageUrls: 'చిత్ర URLs (కామాతో వేరు చేయండి)',
    hotDeal: 'హాట్ డీల్',
    soldStatus: 'అమ్మకం స్థితి',
    login: 'లాగిన్',
    password: 'పాస్‌వర్డ్',
    enterPassword: 'ఎడ్మిన్ పాస్‌వర్డ్ ఎంటర్ చేయండి',
    wrongPassword: 'తప్పు పాస్‌వర్డ్',
    bedrooms: 'పడక గదులు',
    bhk: 'BHK',
    contactAgent: 'ఏజెంట్‌ను సంప్రదించండి',
    poweredBy: 'నల్గొండ రియల్ ఎస్టేట్ కోసం నిర్మించబడింది',
    language: 'భాష',
    English: 'English',
    Telugu: 'తెలుగు',
    Hindi: 'हिन्दी',
    priceRange: 'ధర పరిధి',
    min: 'కనిష్ఠ',
    max: 'గరిష్ట',
    inquireMsg: 'నమస్కారం, నేను మీ ఆస్తిపై ఆసక్తిగా ఉన్నాను',
    // ---- NEW: Media support ----
    uploadFile: 'మీడియా ఫైల్‌లను అప్‌లోడ్ చేయండి',
    uploadImages: 'మీడియా ఫైల్‌లను అప్‌లోడ్ చేయండి',
    imageHint: 'ఇమేజ్‌లు మరియు వీడియోలను అప్‌లోడ్ చేయండి. ఆటో-కంప్రెస్‌డ్. ఫైల్‌కు గరిష్టంగా 500 MB.',
    removeImage: 'తొలగించు',
    mediaFile: 'మీడియా ఫైల్',
    chooseFile: 'ఫైల్ను ఎంచుకోండి',
    translate: 'తెలుగు & హిందీలోకి ఆటో-అనువదించండి',
    translating: 'అనువదిస్తోంది…',
    retranslate: 'మళ్లీ అనువదించు',
    autoTranslated: 'ఆటో-అనువదించబడింది. అవసరమైతే మార్చండి.',
  },
  hi: {
    appName: 'नालगोंडा एस्टेट्स',
    tagline: 'नालगोंडा के आस-पास प्रीमियम ज़मीन, प्लॉट और घर',
    search: 'गांव, कॉलोनी, क्षेत्र खोजें...',
    filters: 'फिल्टर',
    location: 'स्थान',
    allLocations: 'सभी स्थान',
    propertyType: 'संपत्ति प्रकार',
    all: 'सभी',
    agriculture: 'कृषि भूमि',
    plot: 'प्लॉट',
    house: 'घर',
    sortBy: 'चुनें',
    priceLowToHigh: 'कीमत: कम से ज़्यादा',
    priceHighToLow: 'कीमत: ज़्यादा से कम',
    newest: 'नए पहले',
    hotDeals: 'हॉट डील्स',
    featured: '🔥 हॉट',
    sold: 'बिक गया',
    saved: 'सहेजा',
    savedListings: 'सहेजी गई संपत्तियां',
    noSaved: 'अभी तक कोई संपत्ति सहेजी नहीं गई।',
    village: 'गांव',
    colony: 'कॉलोनी / क्षेत्र',
    costPerAcre: 'प्रति एकड़ कीमत',
    costPerSqYard: 'प्रति वर्ग गज कीमत',
    totalArea: 'कुल क्षेत्रफल',
    builtUpArea: 'निर्मित क्षेत्र',
    plotArea: 'प्लॉट क्षेत्र',
    totalCost: 'कुल कीमत',
    acres: 'एकड़',
    sqYards: 'वर्ग गज',
    sqft: 'वर्ग फुट',
    call: 'कॉल',
    sms: 'एसएमएस',
    whatsapp: 'व्हाट्सएप',
    share: 'शेयर',
    viewDetails: 'विवरण देखें',
    showing: 'दिखा रहे हैं',
    properties: 'संपत्तियां',
    noResults: 'आपके फिल्टर से मेल खाती कोई संपत्ति नहीं।',
    clearFilters: 'फिल्टर साफ करें',
    admin: 'एडमिन',
    backToSite: 'साइट पर वापस',
    agentDashboard: 'एजेंट डैशबोर्ड',
    addListing: 'लिस्टिंग जोड़ें',
    editListing: 'लिस्टिंग संपादित करें',
    listings: 'लिस्टिंग',
    actions: 'कार्य',
    toggleSold: 'बिका/नहीं टॉगल',
    delete: 'हटाएं',
    edit: 'संपादित',
    save: 'सहेजें',
    cancel: 'रद्द',
    type: 'प्रकार',
    locationLabel: 'स्थान',
    titleEn: 'शीर्षक (अंग्रेज़ी)',
    titleTe: 'शीर्षक (तेलुगु)',
    titleHi: 'शीर्षक (हिंदी)',
    descEn: 'विवरण (अंग्रेज़ी)',
    descTe: 'विवरण (तेलुगु)',
    descHi: 'विवरण (हिंदी)',
    imageUrls: 'चित्र URL (अल्पविराम से अलग)',
    hotDeal: 'हॉट डील',
    soldStatus: 'बिक्री स्थिति',
    login: 'लॉगिन',
    password: 'पासवर्ड',
    enterPassword: 'एडमिन पासवर्ड डालें',
    wrongPassword: 'गलत पासवर्ड',
    bedrooms: 'बेडरूम',
    bhk: 'BHK',
    contactAgent: 'एजेंट से संपर्क करें',
    poweredBy: 'नालगोंडा रियल एस्टेट के लिए बनाया गया',
    language: 'भाषा',
    English: 'English',
    Telugu: 'तेलुगु',
    Hindi: 'हिन्दी',
    priceRange: 'कीमत सीमा',
    min: 'न्यूनतम',
    max: 'अधिकतम',
    inquireMsg: 'नमस्ते, मुझे आपकी संपत्ति में रुचि है',
    // ---- NEW: Media support ----
    uploadFile: 'मीडिया फ़ाइलें अपलोड करें',
    uploadImages: 'मीडिया फ़ाइलें अपलोड करें',
    imageHint: 'छवियों और वीडियो को अपलोड करें। ऑटो-कंप्रेस्ड। फ़ाइल के प्रति अधिकतम 500 MB।',
    removeImage: 'हटाएं',
    mediaFile: 'मीडिया फ़ाइल',
    chooseFile: 'फ़ाइल चुनें',
    translate: 'तेलुगु और हिंदी में ऑटो-अनुवाद करें',
    translating: 'अनुवाद हो रहा है…',
    retranslate: 'फिर से अनुवाद करें',
    autoTranslated: 'ऑटो-अनुवादित। ज़रूरत हो तो संपादित करें।',
  },
};

// Seed mock properties
export const SEED_PROPERTIES = [
  {
    id: 'p-001',
    type: 'agriculture',
    location: 'Nalgonda',
    village: 'Chityala',
    villageTe: 'చిట్యాల',
    villageHi: 'चिट्याला',
    title: { en: 'Fertile Farmland near Chityala', te: 'చిట్యాల సమీపంలో సుముఖమైన భూమి', hi: 'चिट्याला के पास उपजाऊ भूमि' },
    description: { en: 'Black soil, bore well, road access, near highway.', te: 'నల్లరేగడి, బోర్ వెల్, రోడ్ ప్రవేశం', hi: 'काली मिट्टी, बोर वेल, सड़क पहुंच' },
    areaAcres: 5,
    pricePerAcre: 1200000,
    totalPrice: 6000000,
    images: ['https://images.unsplash.com/photo-1495107334309-fcf20504a5ab?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200', 'https://images.unsplash.com/photo-1548941489-3e64750ebbaa?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200'],
    hotDeal: true,
    sold: false,
    createdAt: Date.now() - 100000,
  },
  {
    id: 'p-002',
    type: 'plot',
    location: 'Nalgonda',
    colony: 'Vivekananda Nagar',
    colonyTe: 'వివేకానంద నగర్',
    colonyHi: 'विवेकानंद नगर',
    title: { en: 'HMDA Plot in Vivekananda Nagar', te: 'వివేకానంద నగర్‌లో HMDA ప్లాటు', hi: 'विवेकानंद नगर में HMDA प्लॉट' },
    description: { en: 'Corner plot, east facing, gated community.', te: 'మూల ప్లాటు, తూర్పు ముఖం', hi: 'कोने का प्लॉट, पूर्व की ओर' },
    areaSqYards: 200,
    pricePerSqYard: 12000,
    totalPrice: 2400000,
    images: ['https://images.unsplash.com/photo-1461175827210-5ceac3e39dd2?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200', 'https://images.unsplash.com/photo-1587745890135-20db8c79b027?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200'],
    hotDeal: true,
    sold: false,
    createdAt: Date.now() - 80000,
  },
  {
    id: 'p-003',
    type: 'house',
    location: 'Nalgonda',
    colony: 'NGO Colony',
    colonyTe: 'NGO కాలనీ',
    colonyHi: 'NGO कॉलोनी',
    title: { en: '3 BHK Independent House', te: '3 BHK స్వతంత్ర ఇల్లు', hi: '3 BHK स्वतंत्र घर' },
    description: { en: 'Newly built, modular kitchen, parking for 2 cars.', te: 'కొత్తగా నిర్మించిన ఇల్లు', hi: 'नया बना हुआ, मॉड्यूलर किचन' },
    plotArea: 200,
    builtUpArea: 1800,
    bedrooms: 3,
    totalPrice: 7500000,
    images: ['https://images.unsplash.com/photo-1660915076159-def99bbbc1bb?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200', 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200'],
    hotDeal: false,
    sold: false,
    createdAt: Date.now() - 60000,
  },
  {
    id: 'p-004',
    type: 'agriculture',
    location: 'Miryalaguda',
    village: 'Damaracharla',
    villageTe: 'దామరచర్ల',
    villageHi: 'दामरचर्ला',
    title: { en: 'Canal-fed Paddy Field', te: 'కాలువకింద నీటి వరి పొలం', hi: 'नहर का पानी वाला धान का खेत' },
    description: { en: 'Year-round water from Nagarjuna Sagar canal.', te: 'నాగార్జునసాగర్ కాలువ నీరు', hi: 'नागार्जुन सागर नहर का पानी' },
    areaAcres: 10,
    pricePerAcre: 900000,
    totalPrice: 9000000,
    images: ['https://images.unsplash.com/photo-1548941489-3e64750ebbaa?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200', 'https://images.pexels.com/photos/8028860/pexels-photo-8028860.jpeg?auto=compress&cs=tinysrgb&w=1200'],
    hotDeal: false,
    sold: false,
    createdAt: Date.now() - 40000,
  },
  {
    id: 'p-005',
    type: 'plot',
    location: 'Suryapet',
    colony: 'Highway Heights',
    colonyTe: 'హైవే హైట్స్',
    colonyHi: 'हाइवे हाइट्स',
    title: { en: 'Commercial Plot on NH-65', te: 'NH-65 పై వ్యాపార ప్లాటు', hi: 'NH-65 पर वाणिज्यिक प्लॉट' },
    description: { en: 'Prime road frontage, ideal for showroom.', te: 'రోడ్ ఫ్రంటేజు, షోరూముకు అనువు', hi: 'सड़क पर सामने, दुकान के लिए आदर्श' },
    areaSqYards: 500,
    pricePerSqYard: 25000,
    totalPrice: 12500000,
    images: ['https://images.unsplash.com/photo-1773215023063-e662ea91a69c?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200', 'https://images.unsplash.com/photo-1587745890135-20db8c79b027?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200'],
    hotDeal: true,
    sold: false,
    createdAt: Date.now() - 20000,
  },
  {
    id: 'p-006',
    type: 'house',
    location: 'Nalgonda',
    colony: 'Prakash Nagar',
    colonyTe: 'ప్రకాశ్ నగర్',
    colonyHi: 'प्रकाश नगर',
    title: { en: '2 BHK Budget House', te: '2 BHK బజెట్ ఇల్లు', hi: '2 BHK किफायती घर' },
    description: { en: 'Compact, ready-to-move, near school.', te: 'సిద్ధంగా ఉన్నది, పాఠశాల సమీపంలో', hi: 'तुरंत रहने लायक, स्कूल के पास' },
    plotArea: 120,
    builtUpArea: 950,
    bedrooms: 2,
    totalPrice: 3500000,
    images: ['https://images.unsplash.com/photo-1580587771525-78b9dba3b914?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200', 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200'],
    hotDeal: false,
    sold: true,
    createdAt: Date.now() - 10000,
  },
];

export function formatINR(n) {
  if (n == null || isNaN(n)) return '₹0';
  const num = Number(n);
  if (num >= 10000000) return '₹' + (num / 10000000).toFixed(2) + ' Cr';
  if (num >= 100000) return '₹' + (num / 100000).toFixed(2) + ' L';
  if (num >= 1000) return '₹' + (num / 1000).toFixed(1) + 'K';
  return '₹' + num.toLocaleString('en-IN');
}
